### ISSUE TITLE
warning messages during package loading

### ISSUE THREAD

**Issue by SabrielxD** [isoverse/isoorbiGUI#10]
resolve the following imports while loading the isoorbi package in RStudio:
![image](https://user-images.githubusercontent.com/88430615/179322107-49b855a2-eaf4-44e4-9bc5-72aed0676ece.png)

**Comment by 123caj** [comment]
Fixed by changing `package.R`

```
#' @rawNamespace import(DT, except = c(dataTableOutput, renderDataTable))
#' @rawNamespace import(ggplot2, except = last_plot)
```
