### ISSUE TITLE
Dual inlet module - loading test file - warnings

### ISSUE THREAD

**Issue by SabrielxD** [isoverse/isoorbiGUI#11]
below are warnings that appeared in RStudio after loading the dual inlet test file, not sure what it means

![image](https://user-images.githubusercontent.com/88430615/179323306-fe68fd8d-f57a-4558-af00-78c698fcd46f.png)

**Comment by 123caj** [comment]
Fixed by adding `by = c(...)` to `anti_join function`; removed 'Select' extension (was no longer relevant)
