### ISSUE TITLE
Add dependency for shinyWidgets

### ISSUE THREAD

**Issue by 123caj** [isoverse/isoorbiGUI#2]
@SabrielxD Currently shinyWidgets is not installed and loaded automatically...

**Comment by SabrielxD** [comment]
today while opening iso_start_orbitrap_gui(), I have not received the error saying that shinyWidgets needs to be loaded prior to that, as we saw last week. let's see if it happens again at some later point

**Comment by 123caj** [comment]
This should be solved now
