### ISSUE TITLE
dual inlet - data not sorted by block number in output table and file

### ISSUE THREAD

**Issue by SabrielxD** [isoverse/isoorbiGUI#39]
I have found a bug on dual-inlet tab on both https://isoorbi.shinyapps.io/IsoXL/ and https://isoorbi.shinyapps.io/IsoXL-dev/.
In the output data and in the downloaded *.xlsx file, data are not sorted by block number (by time of analysis) as it always was, but the different "sample" names are now grouped together, see below
![image](https://user-images.githubusercontent.com/88430615/235551164-03307e33-bedc-4b9b-a2ff-b0b45eab800e.png)

**Comment by 123caj** [comment]
should be fixed in version 0.52 and later
